# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[kubernetes]
format = 'on [⛵ $context](dimmed green) '
disabled = false

[python]
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
pyenv_prefix = ""
#pyenv_version_name = true

